"use client";
import { useMemo, useState } from "react";
import type { AuditReport, Category, Severity } from "@/lib/types";

const categories: Category[] = ["Technical", "On-page", "Performance", "Mobile UX", "Accessibility", "Indexing", "Trust"];
const severityOrder: Severity[] = ["critical", "high", "medium", "low", "notice", "pass"];
const label = (severity: Severity) => severity === "pass" ? "Passed" : severity;
export function AuditReport({ report }: { report: AuditReport }) {
  const [severity, setSeverity] = useState<Severity | "all">("all"); const [category, setCategory] = useState<Category | "all">("all");
  const findings = useMemo(() => report.findings.filter(f => (severity === "all" || f.severity === severity) && (category === "all" || f.category === category)).sort((a,b) => severityOrder.indexOf(a.severity)-severityOrder.indexOf(b.severity)), [report, severity, category]);
  const download = (format: "json" | "csv") => {
    const value = format === "json" ? JSON.stringify(report, null, 2) : ["severity,category,title,affected_url,evidence,fix,search_impact,verification", ...report.findings.map(f => [f.severity,f.category,f.title,f.affectedUrl,f.evidence,f.fix,f.searchImpact,f.verify].map(v => `\"${v.replaceAll('\"','\"\"')}\"`).join(","))].join("\n");
    const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([value], { type: format === "json" ? "application/json" : "text/csv" })); a.download = `seovux-${report.id}.${format}`; a.click(); URL.revokeObjectURL(a.href);
  };
  return <div className="report">
    <header className="report-top"><div><div className="eyebrow">AUDIT COMPLETE · {new Date(report.auditedAt).toLocaleString()}</div><h2>{new URL(report.finalUrl).hostname}</h2><p className="muted">Final URL: <a href={report.finalUrl} target="_blank">{report.finalUrl}</a> · {report.durationMs}ms</p></div><div className="exports"><button onClick={() => download("csv")}>Export CSV</button><button onClick={() => download("json")}>Export JSON</button><button onClick={() => window.print()}>Print / PDF</button></div></header>
    <div className="overview"><div className="score"><svg viewBox="0 0 42 42"><circle className="track" cx="21" cy="21" r="15.9"/><circle className="meter" cx="21" cy="21" r="15.9" strokeDasharray={`${report.score} ${100-report.score}`} /></svg><div><strong>{report.score}</strong><span>/ 100</span></div></div><div><span className={`pill ${report.indexability === "Indexable" ? "good" : "warn"}`}>{report.indexability}</span><h3>SEO health</h3><p>Weighted score from live, evidence-backed checks.</p></div><div className="stat"><b>{report.status}</b><span>final status</span></div><div className="stat"><b>{report.wordCount.toLocaleString()}</b><span>rendered words</span></div><div className="stat"><b>{report.findings.filter(f=>["critical","high"].includes(f.severity)).length}</b><span>priority issues</span></div></div>
    <section className="fixfirst"><div><div className="eyebrow">FIX FIRST</div><h3>Highest impact, lowest friction</h3></div><ol>{report.findings.filter(f=>["critical","high","medium"].includes(f.severity)).slice(0,3).map(f=><li key={f.id}><span className={`dot ${f.severity}`}/><div><b>{f.title}</b><small>{f.fix}</small></div></li>)}</ol></section>
    <section className="scorecards">{categories.map(c => <div className="card" key={c}><span>{c}</span><b>{report.categoryScores[c]}</b><div><i style={{width:`${report.categoryScores[c]}%`}}/></div></div>)}</section>
    <section className="facts"><div><span>Page title</span><b>{report.title ?? "Not found"}</b></div><div><span>Meta description</span><b>{report.description ?? "Not found"}</b></div><div><span>Canonical</span><b>{report.canonical ?? "Not found"}</b></div><div><span>Robots directive</span><b>{report.robots ?? "Not set"}</b></div></section>
    <section className="findings"><div className="section-header"><div><div className="eyebrow">EVIDENCE-BASED FINDINGS</div><h3>{findings.length} checks shown</h3></div><div className="filters"><select value={severity} onChange={e=>setSeverity(e.target.value as Severity|"all")}><option value="all">All severities</option>{severityOrder.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value as Category|"all")}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div></div>{findings.map(f=><details className="finding" key={f.id}><summary><span className={`severity ${f.severity}`}>{label(f.severity)}</span><div><b>{f.title}</b><small>{f.category} · {f.affectedUrl}</small></div><span className="chev">⌄</span></summary><div className="evidence"><p><b>Why it matters</b>{f.why}</p><p><b>Evidence found</b><code>{f.evidence}</code></p><p><b>{f.severity === "pass" ? "Keep it healthy" : "Specific fix"}</b>{f.fix}</p><p><b>Search visibility context</b>{f.searchImpact}</p><p><b>How to verify</b>{f.verify}</p></div></details>)}</section>
    <section className="technical-grid"><article><div className="eyebrow">REQUEST JOURNEY</div><h3>Redirect chain</h3>{report.redirects.map((r,i)=><div className="hop" key={i}><b>{r.status}</b><span>{r.url}</span><small>{r.target ? `→ ${r.target}` : r.type}</small></div>)}</article><article><div className="eyebrow">RENDER DIFFERENCE</div><h3>Raw HTML vs rendered DOM</h3><p className="muted">{report.rawVsRendered.changed ? "JavaScript materially changed the page." : "No material SEO element changed after rendering."}</p>{report.rawVsRendered.details.map(x=><div className="change" key={x}>{x}</div>)}</article></section>
    {(report.screenshots.desktop || report.screenshots.mobile) && <section className="shots"><div><div className="eyebrow">RENDERED EVIDENCE</div><h3>Desktop and mobile</h3></div><div className="shot-grid">{report.screenshots.desktop && <figure><img src={report.screenshots.desktop} alt="Desktop render"/><figcaption>Desktop · 1440px</figcaption></figure>}{report.screenshots.mobile && <figure><img src={report.screenshots.mobile} alt="Mobile render"/><figcaption>Mobile · 390px</figcaption></figure>}</div></section>}
    {report.checksNotRun.length > 0 && <section className="notrun"><b>Checks not run</b>{report.checksNotRun.map(x=><span key={x}>{x}</span>)}</section>}
  </div>;
}
