import { chromium, devices } from "playwright";
import { assertPublicUrl, normalizeUrl } from "./security";
import type { AuditReport, Category, Finding, Redirect, Severity } from "./types";

const timeout = 22_000;
const agent = "SEOvuxBot/1.0 (+https://seovux.example/bot; audit)";
const attr = (html: string, name: string) => new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']*)`, "i").exec(html)?.[1] ?? new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:name|property)=["']${name}["']`, "i").exec(html)?.[1] ?? null;
const tag = (html: string, name: string) => new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`, "i").exec(html)?.[1]?.replace(/<[^>]+>/g, " ").replace(/\s+/g," ").trim() ?? null;
const rel = (html: string, name: string) => new RegExp(`<link[^>]+rel=["'][^"']*${name}[^"']*["'][^>]+href=["']([^"']*)`, "i").exec(html)?.[1] ?? null;
function words(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/gi," ").replace(/\s+/g," ").trim().split(" ").filter(Boolean).length; }
function text(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>/gi," ").replace(/\s+/g," ").trim(); }
function f(id:string, category:Category, severity:Severity, title:string, affectedUrl:string, why:string, evidence:string, fix:string, points:number): Finding {
  const passed = severity === "pass";
  return { id, category, severity, title, affectedUrl, why, evidence, fix,
    searchImpact: passed ? "This signal is in a healthy state. Keeping it stable helps search engines crawl and understand the page consistently." : "Addressing this can improve how reliably search engines crawl, understand, and present the page. It supports visibility but does not guarantee a ranking change.",
    verify: passed ? "Re-run this audit after material site changes to make sure the signal remains healthy." : "Implement the change, deploy it, then re-run this audit. For indexed pages, use Google Search Console’s URL Inspection and request reindexing when appropriate.", points };
}
async function fetchWithRedirects(start: URL) {
  let current = start; const redirects: Redirect[] = []; let response: Response | undefined;
  for(let i=0;i<10;i++) { await assertPublicUrl(current); response = await fetch(current, { redirect:"manual", headers:{ "user-agent":agent, accept:"text/html,application/xhtml+xml" }, signal:AbortSignal.timeout(timeout) }); const location = response.headers.get("location");
    if(response.status >= 300 && response.status < 400 && location) { const target = new URL(location, current); redirects.push({status:response.status,url:current.toString(),target:target.toString(),type: response.status === 301 || response.status === 308 ? "permanent" : "temporary"}); current=target; continue; }
    redirects.push({status:response.status,url:current.toString(),type:"final"}); return {response,current,redirects}; }
  throw new Error("Redirect limit exceeded (10 hops).");
}
export function calculateScore(findings: Finding[]) { const cats: Category[]=["Technical","On-page","Performance","Mobile UX","Accessibility","Indexing","Trust"]; const result = Object.fromEntries(cats.map(c=>[c,100])) as Record<Category,number>; for(const issue of findings) if(issue.severity !== "pass" && issue.severity !== "notice") result[issue.category]=Math.max(0,result[issue.category]-issue.points); const overall=Math.round(cats.reduce((s,c)=>s+result[c],0)/cats.length); return {overall, result}; }
export function robotsBlocksAll(text: string) { return /user-agent:\s*\*[\s\S]*?disallow:\s*\//i.test(text); }
export async function runAudit(input: string): Promise<AuditReport> {
  const started=Date.now(); const start=normalizeUrl(input); await assertPublicUrl(start);
  const {response,current,redirects}=await fetchWithRedirects(start); const raw=await response.text(); const headers=response.headers; const rawTitle=tag(raw,"title"), rawDescription=attr(raw,"description"), rawCanonical=rel(raw,"canonical");
  const findings: Finding[]=[]; const notRun:string[]=[]; let rendered=raw, screenshotDesktop:string|undefined, screenshotMobile:string|undefined; let browserError:string|undefined; let mobile={overflow:false,tinyTaps:0}; let perf={js:0,css:0,images:0,resources:0,lcp:0,cls:0};
  try { const browser=await chromium.launch({headless:true}); const context=await browser.newContext({userAgent:agent,viewport:{width:1440,height:900},deviceScaleFactor:1,ignoreHTTPSErrors:false}); const page=await context.newPage(); const errors:string[]=[]; page.on("pageerror",e=>errors.push(e.message)); await page.goto(current.toString(),{waitUntil:"domcontentloaded",timeout}); await page.waitForLoadState("networkidle",{timeout:7000}).catch(()=>undefined); await page.evaluate(async()=>{ window.scrollTo(0,document.body.scrollHeight); await new Promise(r=>setTimeout(r,700)); window.scrollTo(0,0); }); rendered=await page.content(); screenshotDesktop=`data:image/png;base64,${(await page.screenshot({fullPage:true,type:"png"})).toString("base64")}`;
    perf=await page.evaluate(()=>{const rs=performance.getEntriesByType("resource") as PerformanceResourceTiming[]; const sum=(kind:string)=>rs.filter(x=>x.initiatorType===kind).reduce((n,x)=>n+(x.transferSize||0),0); const lcp=(performance.getEntriesByType("largest-contentful-paint") as any[]).at(-1)?.startTime||0; const shifts=(performance.getEntriesByType("layout-shift") as any[]).filter(x=>!x.hadRecentInput).reduce((n,x)=>n+x.value,0); return {js:sum("script"),css:sum("link"),images:sum("img"),resources:rs.length,lcp:Math.round(lcp),cls:Math.round(shifts*1000)/1000};});
    const mp=await context.newPage(); await mp.setViewportSize({width:390,height:844}); await mp.goto(current.toString(),{waitUntil:"domcontentloaded",timeout}); await mp.waitForLoadState("networkidle",{timeout:7000}).catch(()=>undefined); mobile=await mp.evaluate(()=>({overflow:document.documentElement.scrollWidth>window.innerWidth+2,tinyTaps:[...document.querySelectorAll("a,button,input,select,textarea")].filter((e:any)=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&(r.width<40||r.height<40)}).length})); screenshotMobile=`data:image/png;base64,${(await mp.screenshot({fullPage:true,type:"png"})).toString("base64")}`; if(errors.length) browserError=`${errors.length} JavaScript error(s), first: ${errors[0]}`; await context.close(); await browser.close(); }
  catch(e) { browserError=e instanceof Error?e.message:"Browser renderer failed"; notRun.push(`Rendered-DOM, mobile, and visual checks were not completed: ${browserError}`); }
  const title=tag(rendered,"title"), description=attr(rendered,"description"), canonical=rel(rendered,"canonical"), robots=attr(rendered,"robots"), lang=/\<html[^>]+lang=["']([^"']+)/i.exec(rendered)?.[1]??null, count=words(rendered); const url=current.toString();
  if(response.status >= 400) findings.push(f("http-status","Technical","critical",`Page returns HTTP ${response.status}`,url,"Error pages are usually not eligible to rank.",`Final response: ${response.status} ${response.statusText}`,"Serve the intended page with a 200 response, or use a purposeful redirect.",35)); else findings.push(f("http-status","Technical","pass",`Final page returns HTTP ${response.status}`,url,"A successful response is a prerequisite for crawling.",`Final response: ${response.status}`,"Keep the final canonical page available.",0));
  if(current.protocol !== "https:") findings.push(f("https","Technical","high","Page is not served over HTTPS",url,"HTTPS is a baseline trust and security signal.",`Final URL uses ${current.protocol}`,"Redirect every HTTP URL to its HTTPS equivalent.",15)); else findings.push(f("https","Technical","pass","HTTPS is enabled",url,"HTTPS protects visitors in transit.",`Final URL uses HTTPS`,"Renew certificates before expiry.",0));
  if(redirects.length>2) findings.push(f("redirects","Technical","medium","Redirect chain has multiple hops",url,"Extra hops slow users and can waste crawl budget.",redirects.map(x=>`${x.status} ${x.url}`).join(" → "),"Point old URLs directly to the final destination.",8));
  if(!canonical) findings.push(f("canonical","Indexing","medium","No canonical URL declared",url,"Canonical hints help consolidate duplicate URL signals.","No <link rel=\"canonical\"> found in the rendered DOM.",`Add <link rel="canonical" href="${url}"> to the page head.`,7)); else if(new URL(canonical,url).toString()!==url) findings.push(f("canonical-conflict","Indexing","medium","Canonical points to a different URL",url,"A different canonical may keep this page out of search results.",`Rendered canonical: ${canonical}`,"Confirm this is intentional; otherwise update it to the final preferred URL.",10)); else findings.push(f("canonical","Indexing","pass","Self-referencing canonical is present",url,"The page clearly signals its preferred URL.",`canonical: ${canonical}`,"Keep it aligned with redirects and sitemap URLs.",0));
  try { const robotsUrl=new URL("/robots.txt",current); await assertPublicUrl(robotsUrl); const robotResponse=await fetch(robotsUrl,{headers:{"user-agent":agent},signal:AbortSignal.timeout(8000)}); const robotText=robotResponse.ok?await robotResponse.text():""; const blockedForAll=/user-agent:\s*\*[\s\S]*?disallow:\s*\//i.test(robotText); if(blockedForAll) findings.push(f("robots","Technical","high","robots.txt blocks all crawlers",url,"A disallow rule can prevent search engines from crawling site content.",`robots.txt at ${robotsUrl} includes User-agent: * with Disallow: /.`,`Review the rule and allow crawling for pages that should appear in search.`,16)); else findings.push(f("robots","Technical","pass","robots.txt is reachable and does not block all crawlers",url, "Crawl controls were checked at the site root.",`robots.txt status: ${robotResponse.status}; ${/sitemap:/i.test(robotText)?"sitemap directive found":"no sitemap directive found"}.`,"Keep crawl directives intentional and expose a sitemap for larger sites.",0)); if(!/sitemap:/i.test(robotText)) findings.push(f("sitemap","Technical","low","No sitemap directive found in robots.txt",url,"A sitemap can help search engines discover canonical URLs, especially on larger sites.",`robots.txt responded ${robotResponse.status} without a Sitemap: line.`,"Add an XML sitemap and declare it with a Sitemap: line in robots.txt.",2)); } catch(e) { notRun.push(`robots.txt could not be checked: ${e instanceof Error?e.message:"request failed"}`); }
  if(/noindex/i.test(robots??"")) findings.push(f("noindex","Indexing","high","Page has a noindex directive",url,"Search engines may omit noindex pages from results.",`meta robots: ${robots}`,"Remove noindex only if this page should appear in search.",18));
  if(!title) findings.push(f("title","On-page","high","Missing page title",url,"The title is a primary relevance and click-through signal.","No <title> found after rendering.","Add one unique, descriptive title of roughly 30–60 characters.",15)); else if(title.length<30||title.length>60) findings.push(f("title-length","On-page","medium","Title length is outside the typical snippet range",url,"Very short or long titles can communicate less clearly or be rewritten.",`Rendered title (${title.length} chars): ${title}`,"Write a specific title around 30–60 characters, with the main topic near the beginning.",6)); else findings.push(f("title","On-page","pass","Title has a healthy length",url, "A clear title helps searchers understand the page.",`Rendered title (${title.length} chars): ${title}`,"Keep it unique across the site.",0));
  if(!description) findings.push(f("description","On-page","medium","Missing meta description",url,"Search engines may use this as a snippet candidate.","No meta[name=description] found in the rendered DOM.","Add a concise, unique summary that describes the page’s benefit.",7));
  else findings.push(f("description","On-page","pass","Meta description is present",url,"A relevant description gives search engines a strong snippet candidate.",`Rendered description (${description.length} chars): ${description}`,"Keep it specific to this page and update it when the page intent changes.",0));
  const h1=(rendered.match(/<h1\b/gi)||[]).length; if(h1!==1) findings.push(f("h1","On-page",h1===0?"high":"medium",h1===0?"No H1 found":"Multiple H1 headings found",url,"A clear primary heading helps communicate the page topic.",`Rendered DOM contains ${h1} H1 element(s).`,h1===0?"Add one descriptive H1 that matches the main page intent.":"Use one primary H1 and demote additional page-section headings.",h1===0?10:5)); else findings.push(f("h1","On-page","pass","Exactly one H1 is present",url,"A single primary heading gives the page a clear main topic.","Rendered DOM contains exactly one H1 element.","Keep the H1 descriptive and aligned with the page’s search intent.",0));
  if(count<250) findings.push(f("thin","On-page","medium","Rendered content may be thin",url,"Very little visible copy can make topical relevance harder to establish.",`Rendered text count: ${count} words.`,"Add useful, original information that answers the visitor’s main question; avoid padding.",8));
  const imgs=[...rendered.matchAll(/<img\b[^>]*>/gi)].map(x=>x[0]); const noAlt=imgs.filter(x=>!/(?:alt=)["'][^"']+["']/i.test(x)).length; if(imgs.length&&noAlt) findings.push(f("alt","Accessibility","low",`${noAlt} image${noAlt===1?"":"s"} missing useful alt text`,url,"Image text alternatives improve accessibility and help search engines understand meaningful images.",`${noAlt} of ${imgs.length} rendered <img> tags have empty or missing alt.`,`Add concise alt text to meaningful images; use alt="" for decorative ones.`,3)); else if(imgs.length) findings.push(f("alt","Accessibility","pass","Rendered images include alt text",url,"Text alternatives make meaningful images more understandable.",`All ${imgs.length} rendered images have non-empty alt text.`,`Keep alt text concise and describe the image purpose rather than repeating nearby copy.`,0));
  const schemas=[...rendered.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]; const invalidSchemas=schemas.filter(x=>{try{JSON.parse(x[1]);return false}catch{return true}}).length; if(!schemas.length) findings.push(f("schema","Technical","low","No JSON-LD structured data detected",url,"Structured data can make eligible content easier for search engines to interpret.","No application/ld+json scripts found in the rendered DOM.","Add only schema markup that accurately represents visible page content.",2)); else if(invalidSchemas) findings.push(f("schema-invalid","Technical","high","Invalid JSON-LD structured data",url,"Invalid markup cannot be reliably processed.",`${invalidSchemas} of ${schemas.length} JSON-LD block(s) failed JSON parsing.`,`Fix the JSON syntax and validate the relevant schema type with Google’s Rich Results Test.`,10));
  if(!attr(rendered,"og:title")) findings.push(f("open-graph","On-page","low","Open Graph title is missing",url,"Social previews can affect sharing and referral traffic.","No og:title meta property in rendered DOM.","Add Open Graph title, description, image, and URL tags.",2)); else findings.push(f("open-graph","On-page","pass","Open Graph title is present",url,"A dedicated social title gives shared links a clearer preview.",`og:title: ${attr(rendered,"og:title")}`,"Keep Open Graph copy aligned with the page title and use a suitable image.",0));
  if(!/name=["']viewport["']/i.test(rendered)) findings.push(f("viewport","Mobile UX","high","Responsive viewport tag is missing",url,"Mobile browsers can render the page at an unsuitable scale.","No meta[name=viewport] found.","Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.",13)); else findings.push(f("viewport","Mobile UX","pass","Responsive viewport is configured",url,"The page tells mobile browsers to use the device width.","Rendered DOM includes a viewport meta tag.","Keep the viewport tag in the document head on every responsive page.",0));
  if(mobile.overflow) findings.push(f("overflow","Mobile UX","medium","Mobile page has horizontal overflow",url,"Sideways scrolling makes content hard to use on small screens.","Rendered mobile document is wider than its 390px viewport.","Find the overflowing element and constrain its width or overflow.",7));
  if(mobile.tinyTaps) findings.push(f("tap-targets","Mobile UX","low",`${mobile.tinyTaps} small tap target${mobile.tinyTaps===1?"":"s"} detected`,url,"Small controls are harder to use on touch screens.",`${mobile.tinyTaps} visible link/button/input elements measured below 40px wide or high.`,"Increase interactive target dimensions and spacing to at least 40-44px where practical.",3));
  if(!lang) findings.push(f("language","Technical","low","Document language is not declared",url,"A language declaration helps search engines and assistive technology interpret the page correctly.","The rendered html element has no lang attribute.","Set the root html lang attribute, for example <html lang=\"en\">.",2)); else findings.push(f("language","Technical","pass","Document language is declared",url,"A declared language supports correct interpretation of the document.",`Rendered html lang: ${lang}`,"Keep it accurate for the primary language of the page.",0));
  if(!/<meta[^>]+charset=/i.test(rendered)) findings.push(f("charset","Technical","low","Character encoding is not explicitly declared",url,"A declared UTF-8 encoding prevents text from being interpreted incorrectly.","No meta charset declaration found in rendered HTML.","Add <meta charset=\"utf-8\"> near the beginning of the document head.",2)); else findings.push(f("charset","Technical","pass","Character encoding is declared",url,"A charset declaration helps preserve text accurately across crawlers and browsers.","Rendered document includes a meta charset declaration.","Keep UTF-8 as the default encoding.",0));
  const insecureResources=current.protocol === "https:" ? (rendered.match(/(?:src|href)=["']http:\/\//gi)||[]).length : 0; if(insecureResources) findings.push(f("mixed-content","Trust","medium","HTTPS page references insecure resources",url,"Mixed content can be blocked by browsers and may weaken visitor trust.",`${insecureResources} rendered resource URL(s) use http:// on an HTTPS page.`,"Update resource URLs to HTTPS or use protocol-safe, same-origin paths.",7)); else if(current.protocol === "https:") findings.push(f("mixed-content","Trust","pass","No obvious mixed-content URLs detected",url,"Keeping page resources secure avoids browser blocking and trust issues.","No rendered src or href attributes begin with http://.","Keep third-party assets on HTTPS and recheck after vendor changes.",0));
  const security=["content-security-policy","strict-transport-security","x-content-type-options"].filter(x=>!headers.get(x)); if(security.length) findings.push(f("headers","Trust","low","Some security headers are missing",url,"Security headers reduce exposure to common browser attacks.",`Missing headers: ${security.join(", ")}.`,`Configure these headers at the origin or CDN after testing compatibility.`,3)); else findings.push(f("headers","Trust","pass","Core security headers are present",url,"Security headers help reduce browser-side exposure and build visitor trust.","Content-Security-Policy, Strict-Transport-Security, and X-Content-Type-Options were returned.","Review header policies after major application changes.",0));
  if(perf.resources){ if(perf.js>700_000) findings.push(f("js-weight","Performance","medium","JavaScript payload is heavy",url,"Large scripts can delay rendering and interaction.",`Rendered page loaded ${(perf.js/1024).toFixed(0)} KB of JavaScript across ${perf.resources} resources.`,"Remove unused JavaScript, defer non-critical scripts, and split large bundles.",7)); if(perf.images>1_000_000) findings.push(f("image-weight","Performance","medium","Image payload is heavy",url,"Large images commonly delay visual loading on mobile.",`Rendered page loaded ${(perf.images/1024).toFixed(0)} KB of image data.`,"Serve responsive AVIF/WebP images and size them to their rendered dimensions.",6)); if(perf.lcp>2500) findings.push(f("lcp","Performance","medium","Estimated LCP is slow",url,"A slower largest visual element can hurt perceived load quality.",`Observed LCP candidate: ${perf.lcp} ms in this controlled audit.`,"Optimize the LCP element, its server response, and render-blocking resources.",7)); if(perf.cls>0.1) findings.push(f("cls","Performance","medium","Layout shifts exceed the recommended threshold",url,"Unexpected movement makes pages frustrating to use.",`Observed cumulative layout shift: ${perf.cls}.`,"Reserve dimensions for images/ads and avoid inserting content above visible content.",6)); }
  if(browserError) findings.push(f("render","Performance","notice","Renderer reported a limitation",url,"The report keeps this transparent so you can judge confidence.",browserError,"Review browser console errors or run the audit again after resolving access restrictions.",0));
  if(rawTitle!==title || rawDescription!==description || rawCanonical!==canonical) findings.push(f("render-diff","Technical","medium","JavaScript changed SEO metadata",url,"Some crawlers may see content differently if rendering fails or is delayed.",`Raw title: ${rawTitle??"none"}; rendered title: ${title??"none"}.`,`Ensure important title, description, canonical, and indexation signals are server-rendered when possible.`,6));
  const {overall,result}=calculateScore(findings); const blocked=/noindex/i.test(robots??"")||response.status>=400; return {id:crypto.randomUUID().slice(0,8),targetUrl:start.toString(),finalUrl:url,status:response.status,score:overall,indexability:blocked?"Blocked":findings.some(x=>x.category==="Indexing"&&["high","medium"].includes(x.severity))?"Needs attention":"Indexable",auditedAt:new Date().toISOString(),durationMs:Date.now()-started,title,description,canonical,robots,language:lang,wordCount:count,categoryScores:result,findings,redirects,screenshots:{desktop:screenshotDesktop,mobile:screenshotMobile},rawVsRendered:{changed:rawTitle!==title||rawDescription!==description||rawCanonical!==canonical,details:[`Title: ${rawTitle??"not set"} → ${title??"not set"}`,`Description: ${rawDescription??"not set"} → ${description??"not set"}`,`Text: ${words(raw)} raw words → ${count} rendered words`]},checksNotRun:notRun};
}
